### ISSUE TITLE
Update user status to registered once email verification completes

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#16] opened 2017-05-10 15:31 UTC
Make sure user update event fires

**Comment by sureshvarman-cronj** [comment] 2017-05-22 13:51
@Arne Once email verification is done, we are making the status to emailVerified, which is already place, but not as registered.

**Comment by gr4per** [comment] 2017-05-22 14:17
@sureshvarman-cronj does this break the existing onboarding case and require changes in onboarding or are we still fine?

**Comment by gr4per** [comment] 2017-05-22 14:52
@celber with this change, do we need updates in onboarding? pls check

**Comment by sureshvarman-cronj** [comment] 2017-05-22 15:53
@Arne, https://github.com/OpusCapita/auth/issues/30, seems to be duplicate for me

**Comment by sureshvarman-cronj** [comment] 2017-05-23 07:22
duplicate of https://github.com/OpusCapita/auth/issues/30

**Closed by sureshvarman-cronj** 2017-05-23 07:22 UTC
