### ISSUE TITLE
No loading indicator for user list

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#95] opened 2018-03-08 09:15 UTC
I see User List and a white page for some extended period.
Here we should have a spinner or similar to indicate data is being loaded

**Comment by StefanDywersant** [comment] 2018-03-09 10:50
There is "Loading" label when data is being downloaded. But it is displayed once UserList component is loaded. UserList is a external service component and it also needs to be downloaded. I bet that that was the cause of white-screen experience. Summing up:

1. you navigated to /bnp/users
2. white-page during UserList service component download (due to service-base-ui it has couple of megs size)
3. UserList displayed
4. "Loading"+grayed table displayed on UserList (probably for short period of time, as user list is small in size)
5. UserList was rendered

**Comment by kwierchris** [comment] 2018-03-09 10:54
We could of course try to use **this.context.showSpinner()** and **this.context.hideSpinner()** from service-base-ui but then we have to make sure that we are able to find out when everything is finally loaded.

**Comment by StefanDywersant** [comment] 2018-03-09 10:57
Can we find out when service component is loaded ?
https://github.com/OpusCapita/bnp/blob/develop/src/client/containers/Admin/UserList.js#L17

**Comment by kwierchris** [comment] 2018-03-09 11:00
That's the problem. This is the source of the loader https://github.com/OpusCapita/react-loaders/blob/master/src/client/components/serviceComponent/serviceComponent.react.js and it uses scriptjs.

**Comment by StefanDywersant** [comment] 2018-03-09 11:06
We could:
1. use inProgressComponent (https://github.com/OpusCapita/react-loaders/blob/master/src/client/components/serviceComponent/serviceComponent.react.js#L13). It has one small downside that it will require developers to implement this every time. Maybe we could come out with some standard inProgressComponent implementation and a possibility to turn it off or overwrite?
2. we could expose a callback fn which will trigger when component is loaded (here: https://github.com/OpusCapita/react-loaders/blob/master/src/client/components/serviceComponent/serviceComponent.react.js#L35)

What do you think?

**Comment by kwierchris** [comment] 2018-03-09 11:11
We do not have real control over this component because it is done by our Minsk friends. What we could do is provide our own small implementation in service-base-ui as it is pretty simple.

**Comment by StefanDywersant** [comment] 2018-03-09 11:18
By our own impl you mean:
1) implementation of inProgressComponent which can be easily injected, like
`
import { InProgressComponent } from '@opuscapita/service-base-ui';
...
serviceComponent({..., inProgressComponent: <InProgressComponent /> })
`

2) our fork of `serviceComponent`

?

**Comment by kwierchris** [comment] 2018-03-09 11:23
Basically creating our own copy of https://github.com/OpusCapita/react-loaders/blob/master/src/client/components/serviceComponent/serviceComponent.react.js in a bit more simple and provide it either as eg. *import { loadServiceComponent } from '@opuscapita/service-base-ui'* or as *this.context.loadServiceComponent*. The first solution could take a callback or return a promise if possible and the second solution could trigger a global event. The second solution would give us more control over the overall components that are in progress to prevent *event flapping*. I did similar stuff with the browser AJAX API.

**Comment by gr4per** [comment] 2018-03-09 12:35
Actually the User list header was displayed but everything white below it (no greyed table at all)


Von: Karol Maciaszek [mailto:notifications@github.com]
Gesendet: Freitag, 9. März 2018 11:50
An: OpusCapita/user <user@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>; Author <author@noreply.github.com>
Betreff: Re: [OpusCapita/user] No loading indicator for user list (#95)


There is "Loading" label when data is being downloaded. But it is displayed once UserList component is loaded. UserList is a external service component and it also needs to be downloaded. I bet that that was the cause of white-screen experience. Summing up:

  1.  you navigated to /bnp/users
  2.  white-page during UserList service component download (due to service-base-ui it has couple of megs size)
  3.  UserList displayed
  4.  "Loading"+grayed table displayed on UserList (probably for short period of time, as user list is small in size)
  5.  UserList was rendered

**Comment by StefanDywersant** [comment] 2018-03-09 12:37
That's because UserList header is rendered by container component which is inside bnp.

https://github.com/OpusCapita/bnp/blob/develop/src/client/containers/Admin/UserList.js#L52

**Comment by StefanDywersant** [comment] 2018-03-21 13:55
Fixed by implementing this: https://github.com/OpusCapita/service-base-ui/pull/18. Integrated to bnp here: https://github.com/OpusCapita/bnp/pull/169.

**Closed by StefanDywersant** 2018-03-21 13:55 UTC
Labels: bug
